title: Xinying(Alicia) Gao # your name (or website title) here
logo: "images/personal pic.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Current IE University Master’s student in International Development with expected graduation in July of 2024. 
  <br><br>
  Having internship experiences in the United Nations and several consulting firms, my working interests lie in the positions of data analytics and business analytics in sustainable/ESG industries. Currently, I am looking for a full-time job/internship opportunity after graduation. 
  <br><br>
  [CV](/pdf/cv_Xinying.pdf)
  <a href="https://www.linkedin.com/in/aliciagao/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
